<?php

/**
 * Implements hook_menu
 * - entry for debuging out of cron
 */
function custom_pdfs_sitemap_menu() {
  $items['admin/config/custom/pdfs-sitemap'] = array(
    'title' => 'Create sitemaps',
    'page callback' => '_custom_generate_sitemap',
    'access arguments' => array('administer configuration'),
    'weight' => 90,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme
 * - theme to build xml
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function custom_pdfs_sitemap_theme($existing, $type, $theme, $path) {
  return array(
    'custom_pdfs_sitemap_xml' => array(
      'template' => 'custom_pdfs_sitemap_xml',
      'variables' => array(
        'items' => array(),
      ),
    ),
  );
}

/**
 * Build sitemap. Menu/cron callback
 * - creates or/and renders the XML file
 * @param bool $isCron
 * @return mixed
 */
function _custom_generate_sitemap($isCron = FALSE) {

  //Reads dir
  $dir = 'pdf';
  $files = file_scan_directory($dir, '`.*\.pdf$`i');

  //Builds XML content
  $build =  array(
    '#items' => $files,
    '#theme' => 'custom_pdfs_sitemap_xml',
  );
  $content = render($build);

  //Creates XML file
  if(!file_put_contents('./sitemap_pdfs.xml', $content)) {
    chmod('./sitemap_pdfs.xml', fileperms('./sitemap_pdfs.xml') | 128 + 16 + 2);
    watchdog('php', 'Unable ro write sitemap for pdfs. Check permissions.');
  }

  //Just renders if not in cron mode
  if(!$isCron) {
    return str_replace("\n", '<br />', htmlentities($content, ENT_QUOTES, 'UTF-8'));
  }

}

/**
 * Implements hook_cron
 * - Rebuids the sitemap
 * - must be used with the uri option when running the cron; example: drush cron --uri=http://custom.local
 */
function custom_pdfs_sitemap_cron() {
  _custom_generate_sitemap(true);
}
